### ISSUE TITLE
libnx: double buffering not working correctly

### ISSUE THREAD

**Issue by Cpasjuste** [gdkchan/Ryujinx#59]
Hi,

There is a problem with double buffering and libnx, at least with "GfxMode_LinearDouble" ("gfxSetMode(GfxMode_LinearDouble)"). The framebuffer is only updated one in two. It works fine on real hw.

**Comment by gdkchan** [comment]
Which method you used to verify that the method is drawing only one of the buffers? From what I tested it should draw both.

**Comment by Cpasjuste** [comment]
Basically :

> for(int i=0; i<10; i++) {
>      drawRect(i*32, 0, w, h); // i*32 = x pos
>      gfxFlushBuffers(); gfxSwapBuffers(); gfxWaitForVsync();
>      printf("FLIP\n");
> }

So i can see the rect moving a frame on two, while it works fine on the device (move each frames).

**Comment by gdkchan** [comment]
May be related to the fact that libnx stuff usually runs locked at 120 fps so half of the frames are dropped. The fix would be implementing the vsync event so they are locked at 60 fps.

**Comment by gdkchan** [comment]
Can you retest with 4314a8f3e5b76bbf2143f701c06e9354de712027? At least the 120 fps issue was fixed.

**Comment by Cpasjuste** [comment]
Hi @gdkchan , unfortunately the problem still persist. I upload a test case if you ever need it : http://files.mydedibox.fr/files/Dev/nx/pfba-1.0.nro

There is three squares which should move at each frame/flip (the emulator svcOutput "FLIP" at each fame/flip), but you can see that they are moving once on two frame.

**Comment by Cpasjuste** [comment]
Thanks @gdkchan, working very fine :)

**Comment by gdkchan** [comment]
Glad its working correctly now, thanks for providing the test.
